server:
  port: 8030
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:./ecommerce_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: